---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.7.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
