---
- name: Install any necessary dependencies [RedHat/Fedora]
  dnf: 
    name: curl
    state: present

- name: Install any necessary PIP dependencies [RedHat/Fedora]
  dnf: 
    name: python-pip
    state: present
  when: influxdb_install_python_client

- name: Add InfluxData repository file [RHEL/Fedora]
  template:
    src: etc/yum.repos.d/influxdata.fedora.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [RHEL/Fedora]
  dnf: 
    name: "{{ influxdb_install_package }}"
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB from URL [RHEL/Fedora]
  dnf: 
    name: "{{ influxdb_install_url }}"
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None

- name: Capture installed InfluxDB version
  command: rpm -q influxdb
  register: reg_influxdb_version

- debug: var=reg_influxdb_version.stdout_lines
