---
- name: Install any necessary dependencies [RedHat/Fedora]
  ansible.builtin.dnf:
    name: curl
    state: present

- name: Install any necessary PIP dependencies [RedHat/Fedora]
  ansible.builtin.dnf:
    name: python-pip
    state: present
  when: influxdb_install_python_client

- name: Add InfluxData repository file [RHEL/Fedora]
  ansible.builtin.template:
    src: etc/yum.repos.d/influxdata.fedora.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: true
    backup: true
    mode: 0644
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [RHEL/Fedora]
  ansible.builtin.dnf:
    name: influxdb
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB from URL [RHEL/Fedora]
  ansible.builtin.dnf:
    name: "{{ influxdb_install_url }}"
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
