---
- name: Install any necessary dependencies [Debian/Ubuntu]
  ansible.builtin.apt:
    name:
      - python3-httplib2
      - python3-apt
      - curl
      - apt-transport-https
      - gpg
      - gpg-agent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install any necessary PIP dependencies [Debian/Ubuntu]
  ansible.builtin.apt:
    name: python-pip
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: influxdb_install_python_client

- name: Import InfluxData GPG signing key [Debian/Ubuntu]
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Add InfluxData repository [Debian/Ubuntu]
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ influxdb_install_version }}
    state: present
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Install InfluxDB packages [Debian/Ubuntu]
  ansible.builtin.apt:
    name: influxdb
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: influxdb_install_url is not defined or influxdb_install_url == None

- name: Download InfluxDB package via URL [Debian/Ubuntu]
  ansible.builtin.get_url:
    url: "{{ influxdb_install_url }}"
    dest: /tmp/influxdb-ansible-download.deb
    mode: 0755
  when: influxdb_install_url is defined and influxdb_install_url != None

- name: Install downloaded InfluxDB package [Debian/Ubuntu]
  ansible.builtin.apt:
    deb: /tmp/influxdb-ansible-download.deb
    state: present
  when: influxdb_install_url is defined and influxdb_install_url != None
