# This section can be removed
[provision]
  # The basic provisioner simply deletes and creates database.
  # If `reset_database` is false, it will not attempt to delete the database
  [provision.basic]
    # If enabled the provisioner will actually run
    enabled = true
    # Address of the instance that is to be provisioned
    address = "{{ groups['influxdb']|first }}:8086"
    # Database the will be created/deleted
    database = "stress"
    # Attempt to delete database
    reset_database = true

# This section cannot be commented out
# To prevent writes set `enabled=false`
# in [write.influx_client.basic]
[write]
  [write.point_generator]
    # The basic point generator will generate points of the form
    # `cpu,host=server-%v,location=us-west value=234 123456`
    [write.point_generator.basic]
      # number of points that will be written for each of the series
      point_count = {{ stress_point_count }}
      # number of series
      series_count = {{ stress_series_count }}
      # How much time between each timestamp
      tick = "{{ stress_tick }}"
      # Randomize timestamp a bit (not functional)
      jitter = {{ stress_jitter }}
      # Precision of points that are being written
      precision = "{{ stress_precision }}"
      # name of the measurement that will be written
      measurement = "{{ stress_measurement_name }}"
      # The date for the first point that is written into influx
      start_date = "{{ stress_start_date }}"
      # Defines a tag for a series
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      [[write.point_generator.basic.tag]]
        key = "origin"
        value = "dc"
      [[write.point_generator.basic.field]]
        key = "user"
        value = "float64" # supported types: float64, int, bool
      [[write.point_generator.basic.field]]
        key = "steal"
        value = "float64" # supported types: float64, int, bool

  [write.influx_client]
    [write.influx_client.basic]
      # If enabled the writer will actually write
      enabled = true
      # Address of the Influxdb instance
      addresses = ["{{ groups['influxdb']|first }}:8086",]
      # stress_test_server runs on port 1234
      # Database that is being written to
      database = "stress"
      # Precision of points that are being written
      precision = "{{ stress_precision }}"
      # Size of batches that are sent to db
      batch_size = {{ stress_batch_size }}
      # Interval between each batch
      #batch_interval = "1s"
      batch_interval = "{{ stress_batch_interval }}"
      # How many concurrent writers to the db
      concurrency = {{ stress_write_concurrency }}
      # ssl enabled?
      ssl = false
      # format of points that are written to influxdb
      format = "line_http" # line_udp (not supported yet), graphite_tcp (not supported yet), graphite_udp (not supported yet)

# This section can be removed
 [read]
  [read.query_generator]
    [read.query_generator.basic]
#      # Template of the query that will be ran against the instance
      #template = "SELECT value+value FROM cpu where host='server-%v'"
      
      template = "SELECT user / steal FROM cpu where host='server-%v'"
      
      # How many times the templated query will be ran
      #query_count = 250
      query_count = {{ stress_query_count }}

  [read.query_client]
    [read.query_client.basic]
      # if enabled the reader will actually read
      enabled = true
      # Address of the instance that will be queried
      addresses = ["{{ groups['influxdb']|first }}:8086"]
      # Database that will be queried
      database = "stress"
      # Interval bewteen queries
      query_interval = "{{ stress_query_interval }}"
      # Number of concurrent queriers
      concurrency = 2

